<?php

namespace addons\Style\common\forms;

use addons\Style\common\models\Qiban;

/**
 * 起版-版式 Form
 *
 *
 */
class QibanFormatForm extends Qiban
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        $rules = [
            [['format_sn', 'format_images'], 'required'],
        ];
        return array_merge(parent::rules() , $rules);
    }



    public function beforeValidate()
    {

        //版式图片
        $format_images = $this->format_images;
        if(is_array($format_images)){
            $this->format_images = implode(',',$format_images);
        }
        //版式视频
        $format_video = $this->format_video;
        if(is_array($format_video)){
            $this->format_video = implode(',',$format_video);
        }


        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

}
