<?php

namespace common\models\common;

use common\models\backend\Member;
use common\models\base\BaseModel;
use Yii;

/**
 * This is the model class for table "common_flow_type".
 *
 * @property int $id ID
 * @property string $name 流程名称
 * @property int $cate 流程分类
 * @property int $method 流程方式(1按顺序 2不按顺序)
 * @property string $users 流程人员(多个用逗号隔开)
 * @property int $creator_id
 * @property int $created_at 创建人
 * @property int $updated_at
 */
class FlowType extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return self::tableFullName("common_flow_type");
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'cate','method'], 'required'],
            [['cate', 'method','status',  'created_at', 'updated_at'], 'integer'],
            [['name'], 'string', 'max' => 80],
            [['users'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '流程名称',
            'cate' => '流程分类',
            'method' => '流程方式',
            'users' => '流程人员',
            'status' => '状态',
            'creator_id' => '创建人',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
        ];
    }

    public function beforeValidate()
    {
        if(isset($this->users['user_id'])){
            $users = $this->users['user_id'];
            if(is_array($users)){
                $this->users = implode(',',$users);
            }
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }


    /**
     * 创建人
     * @return \yii\db\ActiveQuery
     */
    public function getCreator()
    {
        return $this->hasOne(Member::class, ['id'=>'creator_id'])->alias('creator');
    }
}
